# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name': 'employee',
    'category': 'Human Resources',
    'summary': 'employyee',
    'version': '1.0',
    'depends': ['base', 'mail'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/employee.xml',
        'views/contract_type.xml',
        'views/employee_report.xml',
        'views/employee_report_action.xml',
        'views/owl_playground_action.xml',
        'views/contract_renew_wizard.xml',
        'views/contract_dashboard_view.xml',
        'views/contract.xml',
        'views/contract_report.xml',
        'views/menu.xml',
        'data/employee_sequence.xml',
        'data/employee_data.xml',
        'data/province_ward_cron.xml',
        'data/contract_expire_cron.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'employee/static/src/playground.js',
            'employee/static/src/playground.xml',
            'employee/static/src/counter.js',
            'employee/static/src/counter.xml',
            'employee/static/src/card.js',
            'employee/static/src/card.xml',
        ],
    },
    'installable': True,
    'auto_install': True,
    'author': '',
    'license': 'LGPL-3',
}